(source gnu)
(source melpa)
(source marmalade)

(depends-on "color-theme-solarized")
(depends-on "scala-mode2")
(depends-on "flycheck")
(depends-on "flx-ido")
(depends-on "ack-and-a-half")
(depends-on "projectile")
(depends-on "multiple-cursors")
(depends-on "clojure-mode")
(depends-on "rainbow-delimiters")